default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: inventory_accounting_development

  test:
  <<: *default
  database: inventory_accounting_test

production:
  <<: *default
  database: <%=ENV['POSTGRESQL_DATABASE']%>
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['INVENTORY_ACCOUNTING_DATABASE_PASSWORD'] %>
